'use client';
import { useEffect, useState } from 'react';
import { connectWallet, getReadClient, getWriteClient, CONTRACT_ADDRESS, isStudioNet } from '@/lib/genlayer';

type Proposal={id:string; target_id:string; credential_id:string; policy_version:number; status:string; decision:string; context:string; confidence_band?:string; critical_risks?:string; rationale?:string};
const sample:Proposal[]=[];

export default function Home(){
 const [account,setAccount]=useState(''); const [mode,setMode]=useState<'injected'|'browser'|'none'>('none'); const [proposals,setProposals]=useState(sample); const [selected,setSelected]=useState<Proposal|null>(null); const [notice,setNotice]=useState(''); const [busy,setBusy]=useState(false);
 useEffect(()=>{ if(typeof window!=='undefined' && window.ethereum) window.ethereum.on?.('accountsChanged',(a:string[])=>setAccount(a[0]||'')); },[]);
 async function connect(kind:'injected'|'browser'){try{const a=await connectWallet(kind);setAccount(a);setMode(kind);setNotice(kind==='injected'?'Injected wallet connected.':'Browser wallet ready.')}catch(e){setNotice(String(e))}}
 async function refresh(){ if(!CONTRACT_ADDRESS){setNotice('No contract address configured. Add NEXT_PUBLIC_CREDENTIALMESH_ADDRESS to read live state.');return} setBusy(true);try{const c=await getReadClient();const rows=await c.readContract({address:CONTRACT_ADDRESS,functionName:'list_proposals',args:[0,20]}) as Proposal[];setProposals(rows||[]);setNotice('Authoritative state refreshed from StudioNet.')}catch(e){setNotice('Contract unavailable: '+String(e))}finally{setBusy(false)} }
 async function createReview(){if(!account){setNotice('Connect a wallet before creating a review.');return}if(!CONTRACT_ADDRESS){setNotice('Configure a deployed contract address first.');return}setNotice('Draft flow ready — submit exact target, credential, policy version, and context from the dossier form.')} 
 return <main><header className="topbar"><div className="brand"><span className="seal">CM</span><span>Credential<span className="gold">Mesh</span></span></div><div className="network"><span className="dot"/> STUDIONET <small>61999</small></div><div className="wallets"><button className="ghost" onClick={()=>connect('browser')}>Use browser wallet</button><button className="primary" onClick={()=>connect('injected')}>{account?account.slice(0,6)+'…'+account.slice(-4):'Connect injected'}</button></div></header>
 <section className="briefing"><div><p className="eyebrow">PROTOCOL BRIEFING / 01</p><h1>Authority, checked<br/><i>in context.</i></h1><p className="lede">CredentialMesh asks whether a credential satisfies a specific policy, then records a scoped decision that can be challenged and audited.</p><div className="actions"><button className="primary" onClick={createReview}>Open a review <span>↗</span></button><button className="textbtn" onClick={refresh}>{busy?'Reading…':'Read live state'} <span>→</span></button></div></div><aside className="brief-card"><div className="card-label">WHY CONSENSUS</div><p>Meaning lives in the evidence. GenLayer validators interpret the natural-language fit; deterministic rules own identity, expiry, revocation and scope.</p><div className="rule"/><div className="mini"><span>READ MODE</span><strong>{mode==='none'?'Public observer':mode==='injected'?'Injected signer':'Browser signer'}</strong></div><div className="mini"><span>CONTRACT</span><strong>{CONTRACT_ADDRESS?CONTRACT_ADDRESS.slice(0,12)+'…':'Not configured'}</strong></div></aside></section>
 <section className="workspace"><div className="section-head"><div><p className="eyebrow">OPERATIONS VIEW / LIVE</p><h2>Review queue</h2></div><div className="legend"><span><b className="amber"/> requires attention</span><span><b className="violet"/> consensus state</span></div></div><div className="queue">{proposals.length===0?<div className="empty"><div className="empty-mark">⌁</div><h3>No reviews on record</h3><p>This is a real empty state. Connect a signer and open the first credential review, or configure the deployed contract address to read StudioNet.</p><button className="outline" onClick={createReview}>Start first review</button></div>:proposals.map(p=><button className="proposal" key={p.id} onClick={()=>setSelected(p)}><span className="index">{p.id}</span><span className="proposal-main"><strong>{p.context||'Untitled review'}</strong><small>{p.credential_id} · policy v{p.policy_version}</small></span><span className={'status '+p.status.toLowerCase()}>{p.status}</span><span className="arrow">→</span></button>)}</div></section>
 <section className="lower"><div><p className="eyebrow">AUDIT TRAIL</p><h2>Every decision leaves a trace.</h2></div><div className="audit-copy"><p>Issuer authority, evidence scope, policy version and final consequence stay legible after settlement. No prose is allowed to control authority on its own.</p><button className="textbtn" onClick={()=>setNotice('Public audit is read-only and sourced from the contract event log.')}>View public audit <span>→</span></button></div></section>
 {selected&&<div className="drawer" role="dialog"><div className="drawer-inner"><button className="close" onClick={()=>setSelected(null)}>×</button><p className="eyebrow">PROPOSAL DOSSIER</p><h2>{selected.context||selected.id}</h2><div className="dossier-grid"><div><span>STATUS</span><strong>{selected.status}</strong></div><div><span>CREDENTIAL</span><strong>{selected.credential_id}</strong></div><div><span>TARGET</span><strong>{selected.target_id}</strong></div><div><span>POLICY</span><strong>Version {selected.policy_version}</strong></div></div><div className="evidence"><span>STABLE DECISION</span><p>{selected.decision} · {selected.confidence_band||'Awaiting consensus'}</p><small>{selected.rationale||'Validator reasoning will appear here after the contract settles.'}</small></div></div></div>}
 <div className="toast" aria-live="polite">{notice}</div></main>
}
